development:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: baet_db
  username: pd_administrator
  password: purodocs

test:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: baet_test_db
  username: pd_administrator
  password: purodocs
